name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: delete the package-lock.json
      run: cd frontend && rm -rf package-lock.json
      
    - name: Install frontend dependencies
      run:  cd frontend && npm install  

    - name: Run the tests
      run: cd frontend && npm test
      
    - name: Run the Linter test
      run: cd frontend && npm run linter

    - name: Build
      run: cd frontend && npm run build
      
    - name: delete the package-lock.json
      run: cd frontend && rm -rf package-lock.json
      
    - name: delete the package-lock.json
      run: cd frontend && rm -rf yarn.lock 
      
    - name: Deploy Frontend to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "seeds-2021" #Must be unique in Heroku
        heroku_email: "njm7162@autuni.ac.nz"
        heroku_branch: "main"
        appdir: "frontend"
    
    - name: Deploy Backend to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "seeds-2021-api" #Must be unique in Heroku
        heroku_email: "njm7162@autuni.ac.nz"
        heroku_branch: "main"
        appdir: "backend"
